# Generated by Django 4.2.1 on 2023-05-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.URLField()),
            ],
        ),
    ]
